export const documents = [
  {
    category: 'overview',
    slug: 'overview',
    title: 'Overview',
    description:
      '개인 웹서비스와 토이 프로젝트를 위한 중립적이고 단단한 디자인 가이드의 소개와 시작 가이드입니다.',
    sections: [
      'Overview',
      'Background',
      'Design Principles',
      'Tech Stack',
      'Token Architecture',
      'Getting Started',
      'Usage & Patterns',
      'Next Steps',
    ],
  },
  {
    category: 'overview',
    slug: 'getting-started',
    title: 'Getting Started',
    description:
      '내 프로젝트에 토큰과 컴포넌트를 가져와 5분 만에 적용하는 실전 가이드입니다.',
    sections: [
      'Overview',
      'Adoption Strategy',
      'Step 1. Copy Tokens',
      'Step 2. Customize Theme',
      'Step 3. Add Components',
      'Step 4. Dark Mode Setup',
      'Framework Tips',
      'Next Steps',
    ],
  },
  {
    category: 'foundations',
    slug: 'colors',
    title: 'Colors',
    description: '색에 역할을 부여해 일관되고 명확한 경험을 만듭니다.',
    sections: [
      'Overview',
      'Primitive palette',
      'Semantic colors',
      'Token hierarchy',
      'Guidelines',
    ],
  },
  {
    category: 'foundations',
    slug: 'typography',
    title: 'Typography',
    description: '명확한 위계와 편안한 읽기 흐름을 위한 타이포그래피입니다.',
    sections: ['Overview', 'Type scale', 'Usage', 'Guidelines'],
  },
  {
    category: 'foundations',
    slug: 'spacing',
    title: 'Spacing',
    description: '4px 기반의 간격 스케일과 레이아웃 역할을 정의합니다.',
    sections: ['Overview', 'Spacing scale', 'Semantic spacing', 'Guidelines'],
  },
  {
    category: 'foundations',
    slug: 'radius',
    title: 'Radius',
    description:
      '모서리 곡률과 형태(Shape)를 정의하여 일관된 톤앤매너와 시각적 위계를 완성합니다.',
    sections: [
      'Overview',
      'Primitive scale',
      'Semantic shapes',
      'Nested radius',
      'Token hierarchy',
      'Guidelines',
    ],
  },
  {
    category: 'components',
    slug: 'button',
    title: 'Button',
    description:
      '사용자가 행동을 시작하거나 선택을 완료할 때 사용하는 컴포넌트입니다.',
    sections: [
      'Overview',
      'Anatomy',
      'Variants',
      'Sizes',
      'States',
      'Guidelines',
      'API',
      'Code Example',
    ],
  },
  {
    category: 'components',
    slug: 'field',
    title: 'Field',
    description:
      '입력 컨트롤과 레이블, 도움말, 오류 메시지를 하나로 연결합니다.',
    sections: [
      'Overview',
      'Anatomy',
      'States',
      'Character Count',
      'Guidelines',
      'API',
      'Code Example',
    ],
  },
  {
    category: 'components',
    slug: 'input',
    title: 'Input',
    description: '사용자가 텍스트를 입력하고 수정할 수 있는 필드입니다.',
    sections: [
      'Overview',
      'Anatomy',
      'Variants',
      'Sizes',
      'States',
      'Guidelines',
      'API',
      'Code Example',
    ],
  },
  {
    category: 'components',
    slug: 'select',
    title: 'Select',
    description: '미리 정의한 옵션 중 하나를 선택하는 필드입니다.',
    sections: [
      'Overview',
      'Anatomy',
      'Variants',
      'Sizes',
      'States',
      'Guidelines',
      'API',
      'Code Example',
    ],
  },
  {
    category: 'components',
    slug: 'textarea',
    title: 'Textarea',
    description: '사용자가 여러 줄의 긴 텍스트를 입력하고 수정하는 필드입니다.',
    sections: [
      'Overview',
      'Anatomy',
      'Sizes',
      'States',
      'Guidelines',
      'API',
      'Code Example',
    ],
  },
  {
    category: 'components',
    slug: 'checkbox',
    title: 'Checkbox',
    description:
      '여러 항목 중 하나 이상을 선택하거나 동의/설정 여부를 전환할 때 사용하는 컴포넌트입니다.',
    sections: [
      'Overview',
      'Anatomy',
      'Sizes',
      'States',
      'Variants',
      'Guidelines',
      'API',
      'Code Example',
    ],
  },
  {
    category: 'components',
    slug: 'radio',
    title: 'Radio',
    description:
      '여러 개의 선택지 중 오직 하나의 항목만 상호 배타적으로 선택할 때 사용하는 컴포넌트입니다.',
    sections: [
      'Overview',
      'Anatomy',
      'Sizes',
      'States',
      'Variants',
      'Guidelines',
      'API',
      'Code Example',
    ],
  },
  {
    category: 'components',
    slug: 'switch',
    title: 'Switch',
    description: '설정의 켜짐과 꺼짐 상태를 즉시 전환하는 컴포넌트입니다.',
    sections: [
      'Overview',
      'Anatomy',
      'Sizes',
      'States',
      'Guidelines',
      'API',
      'Code Example',
    ],
  },
  {
    category: 'components',
    slug: 'badge',
    title: 'Badge',
    description:
      '상태, 새로운 기능, 프로모션 또는 카테고리 태그를 한눈에 강조할 때 사용하는 컴포넌트입니다.',
    sections: [
      'Overview',
      'Anatomy',
      'Variants',
      'Appearances',
      'With Icons',
      'Guidelines',
      'API',
      'Code Example',
    ],
  },
] as const;
export type Doc = (typeof documents)[number];
export const sectionId = (title: string) =>
  title.toLowerCase().replaceAll(' ', '-');
